name: BuiltFiles

on: push
# on:
#   push:
#     paths:
#       - '**.js'
#       - '!test/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies and build docs, TypeScript declaration file, kontra.js, and kontra.min.js
      run: |
        npm ci
        npm run build
        npm run dist
      working-directory: ./