name: BuiltFiles

on: push
# on:
#   push:
#     paths:
#       - '**.js'
#       - '!test/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build development and distribution files
      run: |
        npm ci
        npm run build
        npm run dist