name: BuildFiles

on: push
# on:
#   push:
#     paths:
#       - '**.js'
#       - '!test/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Setup node
      uses: actions/setup-node@v1

    - run: npm ci
    - run: npm run build
    - run: npm run dist

    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Commit built files
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}