name: Tests

on:
  # Allow triggering the workflow manually from UI
  workflow_dispatch:
  pull_request:

# Allow a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run unit tests
        run: npm run test

  typescript-test:
    name: Typescript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run typescript tests
        run: |
          npm run build
          npm run test:ts

  permutation-vector-test:
    name: "Permutation Tests: Vector"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run permutation:vector tests
        run: |
          npm run build
          npm run test:permutations vector
