name: Tests

on:
  # Allow triggering the workflow manually from UI
  workflow_dispatch:
  pull_request:

# Allow a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  # Detect file changes in order to run certain jobs only
  change-detection:
    runs-on: ubuntu-latest

    # Required permissions
    permissions:
      pull-requests: read

    # Set job outputs to values from filter step
    outputs:
      vector: ${{ steps.filter.outputs.vector }}
      gameObject: ${{ steps.filter.outputs.gameObject }}

    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          vector:
            - 'src/vector.js'
          gameObject:
            - 'src/gameObject.js'

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run unit tests
        run: npm run test

  typescript-test:
    name: Typescript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run typescript tests
        run: |
          npm run build
          npm run test:ts

  permutation-vector-test:
    name: "Permutation Tests: Vector"
    needs: change-detection
    if: ${{ needs.changes.outputs.vector == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run permutation:vector tests
        run: |
          npm run build
          npm run test:permutations vector

  permutation-gameObject-test:
    name: "Permutation Tests: gameObject"
    needs: change-detection
    if: ${{ needs.changes.outputs.gameObject == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run permutation:gameObject tests
        run: |
          npm run build
          npm run test:permutations gameObject
